### ISSUE TITLE
Invisible text in settings screen

### ISSUE THREAD

**Issue by mbrouw** [hellhond/be.geekness.tado#2]
The structure of the settings screen is there but none of the text is readable. I can enter my login details but cannot see them. So it is working as designed but the design it self is not visible.

[Screenshot](https://forum.athom.com/discussion/comment/20905/#Comment_20905)

**Comment by hellhond** [comment]
I'm guessing you are accessing the Settings in Homey from a mobile device ? I have a similar issue, but my guess is it had something to do with the HTML / CSS layout in Homey. Since the Tado Settings page is correctly visible on my PC. (Chrome) 

If it is causing a problem on a PC, could you provide me with the details of your browser ?

**Comment by mbrouw** [comment]
I am using Chrome on my PC (version 50.0.2661.94 m) and Tablet (Nexus 9) both the same issue.

**Comment by hellhond** [comment]
Aha.. I was still using Chrome 47.x, where the text was still visible. Apparently, the issue is with Chrome 50.x. Just updated my Chrome version, and have the same issue.

Will investigate.
