### ISSUE TITLE
Humidity

### ISSUE THREAD

**Issue by Tim-Brass** [hellhond/be.geekness.tado#3]
Humidity doesn't get updated.

**Comment by hellhond** [comment]
Should be fixed with version 0.5.2, which has been submitted to app store and awaiting Athom approval.

However, there are still other problems with logging Insights, waiting on Athom for feedback.

**Comment by Tim-Brass** [comment]
No improvement with regards to the Humidity

**Comment by hellhond** [comment]
Ok, I think I've found the issue, I was reading the incorrect value from the Tado api.

Since I don't have the humidity option myself, I can't test this at the moment.

Should be able to test this when I receive the new Tado version.

For the moment I've submitted 0.5.3 the store, awaiting approval.

**Comment by hellhond** [comment]
@ZperX created a fork with some code for Humidity, I added it to version 0.5.5, and submitted it to the Homey App store. Waiting for Athom's approval.

Let me know if it works, since I unfortunately cannot test it myself.
